### PR TITLE
Reworked Update Application Logic

### PR DESCRIPTION
**Pull request by JayVee732**
**Reworked Update Application Logic:** Using the logic from [PKHeX](https://github.com/kwsch/PKHeX/blob/master/PKHeX.WinForms/MainWindow/Main.cs#L232), I've reconfigured the logic to check for an update for the application based on the version number from the Assembly information of the application and the version number included for the tag for the Release on GitHub.

Now when performing a new Release version, you'll need to update the Assembly Information in the application by right-clicking on the CP2077 - EasyInstall project in Visual Studio, in Application click on Assembly Information and change the Assembly Version and the File Version from there. I see most of your tags work off of the first 2 numbers for versioning, so the code will only currently detect the first 2 numbers of the Assembly Information.

image

Let me know if you have trouble configuring this.

**Fixed Unnecessary Casting of Types for config.json:** No need to cast to decimal or double in the application.

**Minor Typo Fixes:** Fixed typos throughout the application.

### CODE REVIEW

**Comment by LittleZen** [comment]
Wow ... amazing work as usual! Thank you @JayVee732, i'm learning a lot from your merge ! I just need a bit of time for correctly understand how it works, and then i will merge everything and i will release the version 2.8! 

I will keep you informed about eventual problem i could met in the releasing of new version (first time that i see this logic)

**Comment by LittleZen** [comment]
Hi @JayVee732 ,

I was looking for the changes made with this merge. My question is: you have set-up a new update system that will automatically check for the new version available by using GitHub tags, so every time i release a new version, do i just have to release a new github release, and everybody will receive the notification?

I was looking in this direction cause i think is a really nice idea do the same stuff for the yamashi's patch. The tool, should notify when a new patch is available ! 

I'm still studying it ... in the little free time I have available 😂😅

**Comment by JayVee732** [comment]
Hey @LittleZen,

So yes, when you are now performing a new Release, you'll need to update the Assembly Information outlined in the previous screenshot to match the release you're going to perform (The next version is v2.8 I assume, so you'll update the information in the Assembly Information to 2.8.0.0).

What I've done in comparison to the work you previously did is instead of a local file that has a version number, the version number is contained within the application itself, and instead of a pastebin file that says the newest version, we use the GitHub API to get the latest version number.

You can quickly test out the functionality on your own machine by changing the Assembly Information to something below 2.7.0.0 and you'll get the notification prompt to update.

Thanks!

**Comment by LittleZen** [comment]
Yep!

I've tried it, and it works! Thank you! 

Just need to use the correct tag, and all should works correctly, right?

**Comment by JayVee732** [comment]
Correct, as long as the tags are in the format v{x}.{y} (The tags you've currently been using, v2.7, v2.6, v2.5, etc), it'll notify the program that a new version is available.

**Comment by LittleZen** [comment]
Thank you man! Amazing work !

**Pull request merged**
