### PR TITLE
Use foreach for uninstalling

### PR DESCRIPTION
**Pull request by Saibamen**
Also there is no need to create empty ZIP file before downloading

### CODE REVIEW

**Comment by LittleZen** [comment]
Thank you @Saibamen ! Great work as usual :3 

#Accepted

**Comment by LittleZen** [comment]
Shall we use `try/catch` in the "deletion phase" for don't crash the application and maybe show errors if the program encounter problems ?

**Comment by Saibamen** [comment]
Yes we could do that

**Comment by Saibamen** [comment]
Sorry that was already done in `btnUninstall_Click()`

**Comment by LittleZen** [comment]
i've code that ... and i've miss that 🤣!

**Pull request merged**
