### PR TITLE
Support for 1.0.0

### PR DESCRIPTION
**Pull request by JayVee732**
**Support for 1.0.0:** Added support for the Enable Console command.

**More code cleanup:** Was in the middle of fixing it up when version 1.0.0 dropped, but I have enough done that I'm happy for the time being. Turns out you can use string interpolation and verbatim strings at the same time, so that cleans up some of the path listings. Removed additional variables that were a little bit pointless.

**Changed Diag Boxes for Debugging:** Moved debug boxes to Traces so messages will now appear in the Output window. Makes it a little more tolerable when debugging :P.

### CODE REVIEW

**Comment by JayVee732** [comment]
Version 1.0.1 has been released, no updated need for the application to function.

**Comment by LittleZen** [comment]
Hi @JayVee732 ! Thank you for the code clean-up! I'm learning a lot from your merge. I didn't really understand "enable console" what mean ... can you please explain ? 

EDIT: didn't see the new release of yamashi, thank you as usual my friend !

**Comment by LittleZen** [comment]
Hi @JayVee732 !

meanwhile i'm releasing version 2.5, i didn't really catch this part "Replaces diag windows for debug with traces, program won't freeze as often when debugging."

**Comment by JayVee732** [comment]
@LittleZen The change from `MessageBox.Show` to `Trace.WriteLine` just means that the text in the windows that would appear while debugging are now displayed in the Output console. Just makes it easier to use the application without having to constantly click on the OK button after each dialog box. Just an aesthetic choice.

**Comment by LittleZen** [comment]
Oh ... yes, i was working on this direction (and i was converting all debug messagebox into Console.writeline), can you explain to me the difference between "Trace.WriteLine" and "Console.WriteLine"? They seems to do the same stuff while working with windows form

**Comment by JayVee732** [comment]
Sure thing! Since we're working with a Windows Form Application, `Console.WriteLine()` won't work as it will only display text on a console application. As we're not working on one, we can use `Trace.WriteLine()` instead to display information for debugging.

image

You'll see the Output window in the bottom left of the screenshot above that shows the same text we previously included in the dialog boxes.

**Comment by LittleZen** [comment]
Oh yes, i'm aware about that, i thought Console.WriteLine could write in debug console anyway !

**Pull request merged**
